project_identifier_env: blip-help-center
api_key_env: f5bc5e23edf14ee44bfedc3721992347
base_path: ./
preserve_hierarchy: true
files:
  - source: /docs/*/*.md
    translation: /website/translated_docs/%locale%/%original_file_name%
  - source: /website/i18n/en.json
    translation: /website/i18n/%locale%.json
    languages_mapping: []
